artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data
  source_url: https://raw.githubusercontent.com/krishnaik06/Car-Price-Prediction/master/car%20data.csv
  # https://raw.githubusercontent.com/aravind9722/datasets-for-ML-projects/main/cardekho_dataset.csv
  

data_validation:
  root_dir: artifacts/data
  clean_dir: artifacts/cleaned_data
  all_schema: dict


data_transformation:
  data_dir: artifacts/cleaned_data
  transformed_dir: artifacts/transformed_data
  